name: Output
on:
    workflow_dispatch:
        inputs:
            os:
                description: Operating system
                default: "ubuntu-latest"
                type: string
            node-version:
                description: Node versions
                default: "14,15"
                type: string   
jobs:
    prepare-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix-arrays: ${{ steps.matrix-array.outputs.result }}
        steps:
            - uses: actions/github-script@v6
              id: matrix-array
              with:
                script: "return {os: context.payload.inputs['os'].split(','), 'node-version': context.payload.inputs['node-version'].split(',')}"
                result-encoding: json
            - run: echo '${{ steps.matrix-array.outputs.result }}'

            - run: echo "username=admin" >> $GITHUB_OUTPUT
              id : step-1
            - run: echo "dbname=test" >> $GITHUB_OUTPUT
              id : step-2
            - run:
                echo '${{ steps.step-1.outputs.username }}'
                echo '${{ steps.step-2.outputs.dbname }}'
    node-matrix:
        needs: prepare-matrix
        strategy:
            matrix:
                os: ${{ fromJson(needs.prepare-matrix.outputs.matrix-arrays).os }}
                node-version: ${{ fromJson(needs.prepare-matrix.outputs.matrix-arrays).node-version}}

        runs-on: ${{ matrix.os }}
        steps:
            - run: node -v
            - uses: actions/setup-node@v3
              with: 
                node-version: ${{ matrix.node-version }}
            - run: node -v
  
    



