name: Sample Workflow
on:
  workflow_call:  
    inputs:
     environment:
      required: true
      type: string
 
jobs:
  sample_job:
    runs-on: ubuntu-latest  
    steps:
      - name: sample step
        run: echo "Hello from reusable workflow"