name: Sample Workflow
on:
  workflow_call:  
    inputs:
      environment:
        required: false
        type: string

jobs:
  sample_job:
    runs-on: ubuntu-latest 
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: sample step
        run: echo "Hello from reusable workflow"