name: Sample Workflow
on:
  workflow_call:  

jobs:
  sample_job:
    runs-on: ubuntu-latest 
    environment: Production 
    steps:
      - name: sample step
        run: echo "Hello from reusable workflow"