name: Sample Workflow
on:
  workflow_call:  

jobs:
  sample_job:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: sample step
        run: echo "Hello from reusable workflow"