name: Sample Reusable Workflow

on:
  workflow_call:  
    inputs:
      example_input:
        required: false
        type: string

jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: print msg
        run: echo "Reusable workflow executed"

