name: Task Workflow
on:
  workflow_dispatch:

jobs:
  reusable_workflow_without_approval:
    uses: santoshPagire/git-action/.github/workflows/sample_workflow.yaml@main
    with:
      environment: ""


  reusable_workflow_with_approval:
    needs: reusable_workflow_without_approval
    with:
     environment: Production
    uses: santoshPagire/git-action/.github/workflows/sample_workflow.yaml@main

          