name: Task Workflow
on:
  workflow_dispatch:

jobs:
  reusable_workflow_without_approval: 
    runs-on: ubuntu-latest
    steps:
      - name: call workflow
        uses: santoshPagire/git-action/.github/workflows/sample_workflow.yaml@main


  reusable_workflow_with_approval:
    needs: reusable_workflow_without_approval
    environment: Production
    runs-on: ubuntu-latest
    steps:
        - name: call workflow
          uses: santoshPagire/git-action/.github/workflows/sample_workflow.yaml@main