name: Task Workflow
on:
  workflow_dispatch:

jobs:
  reusable_workflow_without_approval:
    uses: santoshPagire/git-action/.github/workflows/sample_workflow.yaml@main


  reusable_workflow_with_approval:
    needs: reusable_workflow_without_approval
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: call  
        uses: santoshPagire/git-action/.github/workflows/sample_workflow.yaml@main  