name: Task Workflow
on:
  workflow_dispatch:

jobs:
  reusable_workflow_without_approval:
    runs-on: ubuntu-latest
    uses: santoshPagire/git-action/.github/workflows/sample_workflow.yaml@main  # This references the reusable workflow directly

  reusable_workflow_with_approval:
    runs-on: ubuntu-latest
    needs: reusable_workflow_without_approval
    environment: Production
    uses: santoshPagire/git-action/.github/workflows/sample_workflow.yaml@main  # This references the reusable workflow directly
