name: task workflow
on:
    workflow_dispatch:

jobs:
    reusable_workflow_without_approval:
        runs-on: ubuntu-latest
        steps:
            -  uses: ./.github/workflows/sample_workflow.yaml
               secrets: inherit

    reusable_workflow_with_approval:
        runs-on: ubuntu-latest
        needs: reusable_workflow_without_approval
        environment: Production
        steps:
            -  uses: ./.github/workflows/sample_workflow.yaml
               secrets: inherit


    