name: Variables and Secrets
on: 
    workflow_call:
jobs:
  log-vars:
    runs-on: ubuntu-latest
    environment: "staging"
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET=='True'
        run: echo "Boolean value is true"
      - name: Log vars
        run: |
          echo "Env-level-var: $ENV_LEVEL_VAR"
          echo "Repo-level-var: $REPO_LEVEL_VAR"
          